ELearningTest/Models/ErrorViewModel.cs
using System;

namespace ELearningTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ELearningTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ELearningTest.Models;

namespace ELearningTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ELearningTest/Controllers/UserCourseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ELearningTest.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using X.PagedList;

namespace ELearningTest.Controllers
{
    public class UserCourseController : Controller
    {
        private ElearningDbContext _context;
        private IWebHostEnvironment _hostingEnvironment;

        public UserCourseController(ElearningDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        public async  Task<IActionResult> Index(int? page)
        {
            var pageNumber = page ?? 1;
            var userCourse = await _context.UserCourses
                .Include(a=>a.User)
                .Include(a=>a.Course)
                .ToPagedListAsync(pageNumber, 20);

            return View(userCourse);
        }

        [HttpPost]
        public async Task<IActionResult> UploadCourse()
        {
            var file = Request.Form.Files[0];
            string folderName = "UploadedFiles";
            string webRootPath = _hostingEnvironment.WebRootPath;

            string newPath = Path.Combine(webRootPath, folderName);

            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
            }

            var courses = new List<Course>();
            if (file.Length > 0)
            {
                string sFileExtension = Path.GetExtension(file.FileName)?.ToLower();
                ISheet sheet;
                string fullPath = Path.Combine(newPath, file.FileName ?? throw new InvalidOperationException());

                using (var stream = new FileStream(fullPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                    stream.Position = 0;
                    if (sFileExtension == ".xls")
                    {
                        HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //This will read the Excel 97-2000 formats  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook  
                    }
                    else
                    {
                        XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //This will read 2007 Excel format  
                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook   
                    }

                    IRow headerRow = sheet.GetRow(0); //Get Header Row
                    int cellCount = headerRow.LastCellNum;

                    for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++) //Read Excel File
                    {
                        IRow row = sheet.GetRow(i);

                        if (row == null) continue;
                        if (row.Cells.All(d => d.CellType == CellType.Blank)) continue;

                        var course = new Course()
                        {
                            Title = row.GetCell(1).ToString(),
                            Description = row.GetCell(2).ToString(),
                        };
                        courses.Add(course);
                    }

                   await _context.Courses.AddRangeAsync(courses);
                   await _context.SaveChangesAsync();
                   return Ok(new {message = "uploaded successfully"});
                }
             
            }

            return BadRequest("Something went wrong");
        }
    }
}

ELearningTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h3> <a href="@Url.Action("Index", "UserCourse")"> Upload Course Or  View User Course</a></h3>
</div>

ELearningTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ELearningTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ELearningTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ELearningTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ELearningTest/Views/UserCourse/Index.cshtml
@model X.PagedList.IPagedList<ELearningTest.Data.UserCourse>
@using X.PagedList.Mvc.Core; 
@using X.PagedList;
@{
    
}
<style>
    .pagination li {
        padding: 5px;
        margin: 4px;
        border: 2px solid black;
    }
    /*.pagination li.PagedList-skipToNext {
        border-radius: 100%;
        width: 25px;
        height: 35px;
        padding-left: 6px;
       }*/

</style>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-body ">
                <p>Upload Course</p>
                <form id="form">
                    <a href="/course.xlsx">download format</a>
                    <br/>
                    <div class="form-group">
                        <input type="file" name="file" id="file" placeholder="upload excel for course"/>
                    </div>
                    <br/>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>
            </div>
        </div>
        <br/> <br/>
        <div class="col-sm-12">
            <h3>User Courses</h3>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>User</th>
                    <th>Course</th>
                    <th>Time Spent</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var m in Model)
                {
                    <tr>
                        <td>
                            @m.User.FirstName @m.User.LastName
                            <br/> <small>@m.User.Email</small>
                        </td>
                        <td>@m.Course.Title</td>
                        <td>@m.Duration</td>
                    </tr>
                }
                </tbody>
                <tfoot>


                </tfoot>
            </table>
            <div>
                @Html.PagedListPager(Model, page => Url.Action("Index", new {page = page}))
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $("#form").submit(function(e) {
            e.preventDefault();
       
            console.log(data);
            var fileUpload = $("#file").get(0);

            var files = fileUpload.files;

            var data = new FormData();

            data.append(files[0].name, files[0]); 

            $.ajax(
                {
                    url:'@Url.Action("UploadCourse")',
                    type: "post",
                    data: data,
                    contentType: false,

                    processData: false,

    

                    async: false,
                    success: function(res) {
                        alert(res.message);
                    },
                    error: function(error) {
                        alert("Error Uploading File, Ensure your sheet is using the standard format");
                        console.log(error);
                    }
                });
        })
    </script>
}